import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import pc from "picocolors";
import { computeStats, type StatsData } from "../core/stats.js";
import { today, type UsageSummary } from "../core/usage.js";

/**
 * stats 命令:把 usage preset 收集的数据渲染成可晒的报告——
 * 终端总览+柱状图,或 `--share` 生成 SVG 分享卡片。渲染函数均为纯函数。
 */

export interface StatsOptions {
  days?: number;
  json?: boolean;
  /** 生成 SVG 分享卡片的路径(不带值时默认 kimi-boost-stats.svg) */
  share?: string | boolean;
}

function mmdd(day: string): string {
  return day.slice(5); // "2026-09-01" -> "09-01"
}

/** 逐日 prompts 柱状图(按最大值缩放到 width 个块) */
export function renderBarChart(series: UsageSummary[], width = 24): string[] {
  const max = Math.max(0, ...series.map((s) => s.prompts));
  return series.map((s) => {
    const n = max > 0 ? Math.round((s.prompts / max) * width) : 0;
    const bar = "█".repeat(n) || (s.prompts > 0 ? "▏" : "");
    const isToday = s.day === today();
    const label = `${mmdd(s.day)}${isToday ? "*" : ""}`;
    return `${label} ${pc.green(bar)} ${pc.dim(String(s.prompts))}`;
  });
}

/** 终端文本报告(含颜色) */
export function renderTerminalReport(stats: StatsData): string {
  const lines: string[] = [];
  lines.push(pc.bold(`📊 kimi-boost stats · last ${stats.days} days`));
  lines.push("");
  lines.push(
    `  ${pc.bold(String(stats.totals.prompts))} prompts  ·  ${pc.bold(String(stats.totals.sessions))} sessions  ·  ` +
      `${pc.bold(String(stats.totals.toolCalls))} tool calls  ·  ${pc.bold(String(stats.activeDays))} active days  ·  ` +
      `streak ${pc.bold(String(stats.streak))} 🔥`,
  );
  lines.push("");
  lines.push(...renderBarChart(stats.series));
  lines.push("");
  const bits: string[] = [];
  if (stats.bestDay) bits.push(`best day ${stats.bestDay.day} (${stats.bestDay.prompts} prompts)`);
  if (stats.activeDays > 0) bits.push(`avg ${stats.avgPromptsPerActiveDay} prompts/active day`);
  if (stats.totals.minutes > 0) bits.push(`~${stats.totals.minutes}min active`);
  if (bits.length) lines.push(pc.dim(bits.join("  ·  ")));
  if (stats.totals.prompts === 0) {
    lines.push(pc.dim("还没有用量数据——安装 usage preset 后,数据会随每日使用自动累计。"));
  }
  lines.push(pc.dim("* = today"));
  return lines.join("\n");
}

function escapeXml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/** 生成深色分享卡片 SVG(纯字符串模板,无依赖) */
export function generateSvg(stats: StatsData): string {
  const W = 720;
  const H = 320;
  const statsRow: Array<{ label: string; value: string }> = [
    { label: "Prompts", value: String(stats.totals.prompts) },
    { label: "Sessions", value: String(stats.totals.sessions) },
    { label: "Tool calls", value: String(stats.totals.toolCalls) },
    { label: "Active days", value: String(stats.activeDays) },
    { label: "Streak", value: `${stats.streak}d` },
  ];

  // mini 柱状图:窗口内逐日 prompts,按最大值缩放
  const chartTop = 210;
  const chartH = 70;
  const n = stats.series.length;
  const gap = 6;
  const barW = Math.max(2, (W - 64 - gap * (n - 1)) / Math.max(1, n));
  const max = Math.max(1, ...stats.series.map((s) => s.prompts));
  const bars = stats.series
    .map((s, i) => {
      const h = s.prompts > 0 ? Math.max(3, (s.prompts / max) * chartH) : 2;
      const x = 32 + i * (barW + gap);
      const y = chartTop + (chartH - h);
      const fill = s.day === today() ? "#58a6ff" : "#3fb950";
      return `<rect x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${barW.toFixed(1)}" height="${h.toFixed(1)}" rx="2" fill="${fill}"/>`;
    })
    .join("\n    ");

  const colW = (W - 64) / statsRow.length;
  const statCols = statsRow
    .map((c, i) => {
      const x = 32 + i * colW;
      return (
        `<text x="${x.toFixed(1)}" y="150" font-size="30" font-weight="700" fill="#f0f6fc">${escapeXml(c.value)}</text>\n` +
        `    <text x="${x.toFixed(1)}" y="172" font-size="13" fill="#8b949e">${escapeXml(c.label)}</text>`
      );
    })
    .join("\n    ");

  const range = stats.series.length
    ? `${mmdd(stats.series[0].day)} → ${mmdd(stats.series[stats.series.length - 1].day)}`
    : "";

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" font-family="-apple-system,'Segoe UI',Helvetica,Arial,sans-serif">
  <rect width="${W}" height="${H}" rx="12" fill="#0d1117" stroke="#30363d"/>
  <text x="32" y="52" font-size="20" font-weight="700" fill="#f0f6fc">📊 kimi-boost stats</text>
  <text x="32" y="76" font-size="13" fill="#8b949e">last ${stats.days} days · ${escapeXml(range)}</text>
  <text x="${W - 32}" y="52" font-size="13" fill="#8b949e" text-anchor="end">best ${stats.bestDay ? `${escapeXml(mmdd(stats.bestDay.day))} (${stats.bestDay.prompts}p)` : "—"}</text>
    ${statCols}
    ${bars}
  <text x="${W - 32}" y="${H - 20}" font-size="11" fill="#6e7681" text-anchor="end">generated by kimi-boost</text>
</svg>
`;
}

export function runStats(opts: StatsOptions = {}): void {
  const days = Math.min(90, Math.max(1, opts.days ?? 7));
  const stats = computeStats(days);

  if (opts.json) {
    console.log(JSON.stringify(stats, null, 2));
    return;
  }

  console.log(renderTerminalReport(stats));

  if (opts.share !== undefined && opts.share !== false) {
    const out = resolve(typeof opts.share === "string" && opts.share ? opts.share : "kimi-boost-stats.svg");
    writeFileSync(out, generateSvg(stats), "utf8");
    console.log("");
    console.log(`${pc.green("✓")} 分享卡片已生成: ${pc.cyan(out)}`);
    console.log(pc.dim("截图或嵌入 README 晒一下你的 AI 编程用量。"));
  }
}
